// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"database/sql"
	"time"
)

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
	Address      sql.NullString
	PhoneNumber  sql.NullString
	CreatedAt    time.Time
}
